# Generated by Django 2.0.3 on 2018-03-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=225)),
                ('task_id', models.CharField(max_length=225)),
                ('remind_type', models.CharField(max_length=1)),
                ('remind_content', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=225)),
                ('task_title', models.CharField(max_length=225)),
                ('task_parentid', models.CharField(max_length=225)),
                ('user_id', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nickname', models.CharField(max_length=225)),
                ('user_pwd', models.CharField(max_length=225)),
                ('wechat_openid', models.CharField(max_length=225)),
                ('wechat_union', models.CharField(max_length=225)),
                ('user_headimg', models.CharField(max_length=225)),
                ('user_id', models.CharField(max_length=225)),
            ],
        ),
    ]
